### Universal Functions

Traditional Python for loops are magnitudes slower than universal functions designed to operate on vectors.

In [2]:
import numpy as np

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [4]:
# python loop
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.4 s ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# universal function
%timeit (1.0 / big_array)

2 ms ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

#### Overloaded Arithmetic Operators

In [10]:
# most of Python's arithmetic operations are overloaded with UFuncs
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2) # exponentiation
print("x % 2  = ", x % 2)
print("abs(x)", abs(x))

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]
abs(x) [0 1 2 3]


#### Trigonometric functions

In [13]:
theta = np.linspace(0,np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and Logarithms

In [16]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


#### Specifying Output

When working with very large arrays, it can be useful to specify the output of a result.

In [15]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


#### Aggregate Functions

In [17]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [18]:
np.multiply.reduce(x)

120

In [21]:
# similar to add.reduce, but stores intermediate results
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [22]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [23]:
x1 = np.array([1, 2, 3])
x2 = np.array([10, 100, 1000])
np.multiply.outer(x1, x2)

array([[  10,  100, 1000],
       [  20,  200, 2000],
       [  30,  300, 3000]])

#### Broadcasting

Allows for operation on between arrays of different sizes and shapes. In a section to come.